server:
  port: 7777

spring.datasource.url=jdbc:mysql://localhost:3306/bank_office?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Plemiona123!
spring.datasource.driverClassName=com.mysql.jdbc.Driver


spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update