server:
  port: 7777
accounts:
  datasource:
    url: 'jdbc:mysql://localhost:3306/bank_office?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true'
    username: 'root'
    password : 'Plemiona123!'
    driver-class-name: 'com.mysql.jdbc.Driver'
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  allow-get-accounts: false